### ISSUE TITLE
[code search] update preproc. docs w/ python -mspacy download en

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/examples#315] opened 2018-11-06 22:36 UTC
Run of `code_search.dataflow.cli.preprocess_github_dataset` yields error along the lines of " Warning: no model found for 'en'", fixed with:

```python
python -mspacy download en
```

Probably just need that added to the docs, see it's in the docker container.

**Comment by jlewi** [comment] 2018-11-30 14:03
We've since changed the notebook 
https://github.com/kubeflow/examples/blob/master/code_search/code-search.ipynb

So that we submit the Dataflow job by running a prebuilt docker container. So all of the dependencies should be installed. And I think that should be fixed.

We currently don't provide instructions for how to run the github dataset. Using a Docker container makes the most sense to have a reproducible environment.

The only use case I can think of where people might want to run the code not in their docker container would be if they are debugging it.

So we might want to open up an issue for creating instructions aimed at contributors looking to setup a local development environment.

**Closed by jlewi** 2018-11-30 14:03 UTC
Labels: area/example/code_search, priority/p2
